version: '3.9'

services:
  # BAZA PODATAKA
  db:
    image: timescale/timescaledb:latest-pg14
    container_name: iot_db
    environment:
      POSTGRES_USER: kristina
      POSTGRES_PASSWORD: kristina96
      POSTGRES_DB: iot_system
    ports:
      - "5432:5432"
    volumes:
      # - ./podaci_baze:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      
    restart: always

  # BACKEND
  backend:
    build:
      context: ./iot-backend
      dockerfile: Dockerfile
    container_name: iot_backend
    ports:
      - "3000:3000"
    
    volumes:
      - ./iot-backend:/app          
      - /app/node_modules          
    depends_on:
      - db
    restart: always                 
    command: npm run start:dev

  # FRONTEND
  frontend:
    build:
      context: ./iot-frontend
      dockerfile: Dockerfile
    container_name: iot_frontend
    ports:
      - "4200:4200"
    volumes:
      - ./iot-frontend:/app         
      - /app/node_modules
    depends_on:
      - backend
    command: npx ng serve --host 0.0.0.0 --poll 2000

